use burn::tensor::Tensor;

use super::backend::{Backend, cpu_device};

#[cfg(any(feature = "embedding", feature = "reranking"))]
#[test]
fn output_count_rejects_mismatch() {
    use crate::ml::text::validate_output_count;

    let error = validate_output_count("embedding", 2, 1)
        .expect_err("mismatched output count should fail");
    assert_eq!(
        error.to_string(),
        "embedding output count mismatch: expected 2, got 1",
    );
}

/// The CPU device must run real tensor ops, since it is the fallback used on
/// machines without a GPU (e.g. CI).
#[test]
fn cpu_backend_runs_matmul() {
    let device = cpu_device();
    let a =
        Tensor::<Backend, 2>::from_floats([[1.0, 2.0], [3.0, 4.0]], &device);
    let b =
        Tensor::<Backend, 2>::from_floats([[5.0, 6.0], [7.0, 8.0]], &device);
    let out = a
        .matmul(b)
        .into_data()
        .to_vec::<f32>()
        .expect("matmul output to f32");
    assert_eq!(out, vec![19.0, 22.0, 43.0, 50.0]);
}

#[cfg(any(feature = "ocr", feature = "embedding", feature = "reranking"))]
mod matmul {
    use burn::tensor::{Tensor, TensorData};

    use crate::ml::backend::{self, Backend};
    use crate::ml::safe_matmul;

    /// Multiplies matrices with a plain CPU reference implementation.
    fn cpu_matmul(
        a: &[f32],
        b: &[f32],
        m: usize,
        k: usize,
        n: usize,
    ) -> Vec<f32> {
        let mut out = vec![0.0f32; m * n];
        for i in 0..m {
            for j in 0..n {
                let mut acc = 0.0f32;
                for p in 0..k {
                    acc += a[i * k + p] * b[p * n + j];
                }
                out[i * n + j] = acc;
            }
        }
        out
    }

    /// Returns max absolute error against the CPU reference.
    fn max_abs_err(m: usize, k: usize, n: usize) -> f32 {
        let device = backend::active_device();
        let a: Vec<f32> =
            (0..m * k).map(|i| ((i % 17) as f32 - 8.0) * 0.1).collect();
        let b: Vec<f32> =
            (0..k * n).map(|i| ((i % 13) as f32 - 6.0) * 0.1).collect();
        let ta = Tensor::<Backend, 2>::from_data(
            TensorData::new(a.clone(), [m, k]),
            &device,
        );
        let tb = Tensor::<Backend, 2>::from_data(
            TensorData::new(b.clone(), [k, n]),
            &device,
        );
        let got = safe_matmul(ta, tb)
            .into_data()
            .to_vec::<f32>()
            .expect("matmul output to f32");
        let want = cpu_matmul(&a, &b, m, k, n);
        (0..m * n).fold(0.0f32, |acc, i| acc.max((got[i] - want[i]).abs()))
    }

    /// `safe_matmul` must match a CPU reference across model contraction shapes.
    #[test]
    fn matches_cpu_for_large_k() {
        for (m, k, n) in [
            (256usize, 256usize, 128usize),
            (512, 512, 128),
            (1024, 512, 128),
            (512, 1024, 128),
            (256, 2048, 128),
        ] {
            assert!(
                max_abs_err(m, k, n) < 1.0e-2,
                "safe_matmul wrong for M={m} K={k} N={n}"
            );
        }
    }
}

#[cfg(feature = "ocr")]
mod imageproc {
    use crate::ml::imageproc::resize_cubic_cv2;
    use crate::ml::imageproc::resize_linear_cv2;
    use image::{DynamicImage, RgbImage};

    // A deterministic 17x13 RGB source and its `cv2.resize(..., (8, 6))` output
    // for both interpolations, generated by OpenCV (opencv-python). These are
    // byte-for-byte golden vectors guarding the exact fixed-point behaviour
    // (downscaling 17x13 -> 8x6 exercises both passes and the edge taps).
    #[rustfmt::skip]
    const SRC_17X13: &[u8] = &[
        0, 0, 7, 37, 5, 24, 74, 10, 41, 111, 15, 58, 148, 20, 75, 185, 25, 92, 222, 30, 109, 3, 35, 126, 40, 40, 143, 77, 45, 160, 114, 50, 177, 151, 55, 194, 188, 60, 211, 225, 65, 228, 6, 70, 245, 43, 75, 6, 80, 80, 23,
        11, 53, 36, 48, 58, 53, 85, 63, 70, 122, 68, 87, 159, 73, 104, 196, 78, 121, 233, 83, 138, 14, 88, 155, 51, 93, 172, 88, 98, 189, 125, 103, 206, 162, 108, 223, 199, 113, 240, 236, 118, 1, 17, 123, 18, 54, 128, 35, 91, 133, 52,
        22, 106, 65, 59, 111, 82, 96, 116, 99, 133, 121, 116, 170, 126, 133, 207, 131, 150, 244, 136, 167, 25, 141, 184, 62, 146, 201, 99, 151, 218, 136, 156, 235, 173, 161, 252, 210, 166, 13, 247, 171, 30, 28, 176, 47, 65, 181, 64, 102, 186, 81,
        33, 159, 94, 70, 164, 111, 107, 169, 128, 144, 174, 145, 181, 179, 162, 218, 184, 179, 255, 189, 196, 36, 194, 213, 73, 199, 230, 110, 204, 247, 147, 209, 8, 184, 214, 25, 221, 219, 42, 2, 224, 59, 39, 229, 76, 76, 234, 93, 113, 239, 110,
        44, 212, 123, 81, 217, 140, 118, 222, 157, 155, 227, 174, 192, 232, 191, 229, 237, 208, 10, 242, 225, 47, 247, 242, 84, 252, 3, 121, 1, 20, 158, 6, 37, 195, 11, 54, 232, 16, 71, 13, 21, 88, 50, 26, 105, 87, 31, 122, 124, 36, 139,
        55, 9, 152, 92, 14, 169, 129, 19, 186, 166, 24, 203, 203, 29, 220, 240, 34, 237, 21, 39, 254, 58, 44, 15, 95, 49, 32, 132, 54, 49, 169, 59, 66, 206, 64, 83, 243, 69, 100, 24, 74, 117, 61, 79, 134, 98, 84, 151, 135, 89, 168,
        66, 62, 181, 103, 67, 198, 140, 72, 215, 177, 77, 232, 214, 82, 249, 251, 87, 10, 32, 92, 27, 69, 97, 44, 106, 102, 61, 143, 107, 78, 180, 112, 95, 217, 117, 112, 254, 122, 129, 35, 127, 146, 72, 132, 163, 109, 137, 180, 146, 142, 197,
        77, 115, 210, 114, 120, 227, 151, 125, 244, 188, 130, 5, 225, 135, 22, 6, 140, 39, 43, 145, 56, 80, 150, 73, 117, 155, 90, 154, 160, 107, 191, 165, 124, 228, 170, 141, 9, 175, 158, 46, 180, 175, 83, 185, 192, 120, 190, 209, 157, 195, 226,
        88, 168, 239, 125, 173, 0, 162, 178, 17, 199, 183, 34, 236, 188, 51, 17, 193, 68, 54, 198, 85, 91, 203, 102, 128, 208, 119, 165, 213, 136, 202, 218, 153, 239, 223, 170, 20, 228, 187, 57, 233, 204, 94, 238, 221, 131, 243, 238, 168, 248, 255,
        99, 221, 12, 136, 226, 29, 173, 231, 46, 210, 236, 63, 247, 241, 80, 28, 246, 97, 65, 251, 114, 102, 0, 131, 139, 5, 148, 176, 10, 165, 213, 15, 182, 250, 20, 199, 31, 25, 216, 68, 30, 233, 105, 35, 250, 142, 40, 11, 179, 45, 28,
        110, 18, 41, 147, 23, 58, 184, 28, 75, 221, 33, 92, 2, 38, 109, 39, 43, 126, 76, 48, 143, 113, 53, 160, 150, 58, 177, 187, 63, 194, 224, 68, 211, 5, 73, 228, 42, 78, 245, 79, 83, 6, 116, 88, 23, 153, 93, 40, 190, 98, 57,
        121, 71, 70, 158, 76, 87, 195, 81, 104, 232, 86, 121, 13, 91, 138, 50, 96, 155, 87, 101, 172, 124, 106, 189, 161, 111, 206, 198, 116, 223, 235, 121, 240, 16, 126, 1, 53, 131, 18, 90, 136, 35, 127, 141, 52, 164, 146, 69, 201, 151, 86,
        132, 124, 99, 169, 129, 116, 206, 134, 133, 243, 139, 150, 24, 144, 167, 61, 149, 184, 98, 154, 201, 135, 159, 218, 172, 164, 235, 209, 169, 252, 246, 174, 13, 27, 179, 30, 64, 184, 47, 101, 189, 64, 138, 194, 81, 175, 199, 98, 212, 204, 115,
    ];
    #[rustfmt::skip]
    const LINEAR_8X6: &[u8] = &[
        27, 34, 33, 106, 44, 69, 184, 55, 105, 23, 65, 142, 86, 76, 178, 164, 87, 214, 163, 97, 101, 65, 108, 30,
        51, 148, 96, 130, 159, 132, 208, 170, 168, 47, 180, 204, 109, 191, 229, 188, 201, 73, 55, 212, 57, 89, 223, 93,
        75, 29, 159, 153, 39, 195, 232, 50, 231, 55, 61, 47, 133, 50, 48, 212, 60, 84, 35, 71, 120, 113, 82, 156,
        99, 122, 210, 177, 133, 75, 48, 143, 38, 78, 154, 74, 157, 165, 110, 188, 175, 146, 58, 186, 183, 137, 196, 219,
        122, 173, 29, 201, 184, 65, 60, 194, 101, 102, 25, 137, 181, 23, 173, 159, 34, 209, 82, 45, 181, 161, 55, 26,
        146, 96, 91, 225, 106, 128, 48, 117, 164, 126, 128, 200, 205, 138, 229, 27, 149, 16, 106, 160, 52, 185, 170, 88,
    ];
    #[rustfmt::skip]
    const CUBIC_8X6: &[u8] = &[
        23, 28, 29, 103, 39, 66, 182, 50, 102, 18, 60, 139, 86, 71, 176, 165, 82, 220, 168, 93, 82, 68, 103, 18,
        47, 146, 93, 128, 157, 130, 204, 167, 166, 44, 178, 202, 110, 217, 255, 194, 226, 67, 31, 237, 57, 92, 248, 93,
        71, 22, 156, 152, 33, 194, 254, 44, 241, 53, 55, 41, 134, 46, 46, 219, 58, 84, 7, 68, 120, 116, 79, 157,
        95, 123, 212, 176, 134, 63, 28, 145, 36, 78, 157, 75, 158, 168, 112, 193, 178, 148, 62, 189, 184, 141, 200, 223,
        120, 181, 17, 207, 192, 66, 54, 203, 102, 102, 0, 138, 183, 0, 175, 166, 10, 223, 84, 20, 194, 165, 31, 0,
        144, 100, 93, 253, 111, 130, 41, 122, 166, 126, 133, 202, 208, 144, 235, 7, 154, 0, 109, 165, 59, 189, 176, 93,
    ];

    fn src_image() -> DynamicImage {
        let img = RgbImage::from_raw(17, 13, SRC_17X13.to_vec())
            .expect("golden source dimensions match buffer length");
        DynamicImage::ImageRgb8(img)
    }

    #[test]
    fn linear_matches_cv2_golden() {
        let out = resize_linear_cv2(&src_image(), 8, 6);
        assert_eq!(out.as_raw().as_slice(), LINEAR_8X6, "cv2 INTER_LINEAR");
    }

    #[test]
    fn cubic_matches_cv2_golden() {
        let out = resize_cubic_cv2(&src_image(), 8, 6);
        assert_eq!(out.as_raw().as_slice(), CUBIC_8X6, "cv2 INTER_CUBIC");
    }
}
